### ISSUE TITLE
Support custom retry intervals and attempts

### ISSUE THREAD

**Issue by jaypipes** [gdt-dev/gdt#26]
For some plugins like `gdt-kube`, we [retry actions if we fail assertions](https://github.com/gdt-dev/kube?tab=readme-ov-file#timeouts-and-retrying-kubeget-assertions).

We should add the ability to control the retry behaviour. The interval and number of attempts is plugin-specific but we should allow a GDT top-level `retry` field and defaults that overrides retry interval and number of attempts.

Something like this might work:

```yaml
name: matches
description: create a deployment and check the matches condition succeeds
fixtures:
  - kind
defaults:
  retry:
    attempts: 10
    interval: 30s
tests:
  - name: create-deployment
    kube:
      create: testdata/manifests/nginx-deployment.yaml
  - name: deployment-exists
    kube:
      get: deployments/nginx:
    retry:
      attempts: 2
    assert:
      matches:
        spec:
          replicas: 2
          template:
            metadata:
              labels:
                app: nginx
        status:
          readyReplicas: 2
  - name: delete-deployment
    kube:
      delete: deployments/nginx
```
