### ISSUE TITLE
Tests seem to always result in PASS

### ISSUE THREAD

**Issue by Travisivart** [gdt-dev/gdt#8]
I have a custom resource (csn-test1) which is already defined. I am trying to verify that it has a provisioningStatus of Succeeded. The test yaml file is defined as:

```
tests:
 - name: verify-csn
   timeout:
     after: 2m
   wait:
     before: 10s
   kube:
    get: csn/csn-test1
   assert:
     matches:
       status:
         provisioningStatus:
           status: Succeeded
```

It seems like it doesn't matter what the 'status: Succeeded' field is set to, it will always result in a 'PASS' on the test, instead of the expected FAIL. I tried setting the field to 'status: Succ' which should FAIL but the test case still ends in PASS.

In fact, I was able to drop the entire 'matches' so it doesn't have anything to match and it still resulted in PASS. I would have expected it to fail if it has nothing to match on, or at least some sort of compile error if it has an assertion to make but nothing is actually defined for it.

```
tests:
 - name: verify-csn
   timeout:
     after: 2m
   wait:
     before: 10s
   kube:
    get: csn/csn-test1
   assert:
     matches:
```

Maybe something like this:
=== RUN   TestNetwork
    suite_test.go:18: invalid YAML: expected map field at line 9, column 11
--- FAIL: TestNetwork (0.00s)
FAIL
FAIL   test/functional-gdt    0.016s
FAIL

Which you get if you define assert with nothing under it like so:

```
 tests:
 - name: verify-csn
   timeout:
     after: 2m
   wait:
     before: 10s
   kube:
    get: csn/csn-test1
   assert:
```

**Comment by jaypipes** [comment]
OK, I *think* I've figured out at least part of the reason this is happening.

If I change the kube repository's [`testdata/matches.yaml`](https://github.com/gdt-dev/kube/blob/main/testdata/matches.yaml) file's "deployment-matches-expected-fields` test from this:

```yaml
  - name: deployment-matches-expected-fields
    timeout:
      after: 20s
    kube:
      get: deployments/nginx
    assert:
      matches:
        spec:
          replicas: 2
          template:
            metadata:
              labels:
                app: nginx
        status:
          readyReplicas: 2
```

to this:

```
  - name: deployment-matches-expected-fields
    timeout:
      after: 20s
    kube:
      get: deployments/nginx
    assert:
      matches:
        spec:
          replicas: 2
          template:
            metadata:
              labels:
                app: nginx
        status:
          eadyReplicas: 2
```

(Note misspelling of "readyReplicas" as "eadyReplicas")

I get the following results when running `go test -v`:

```
=== RUN   TestMatches
=== RUN   TestMatches/matches
=== RUN   TestMatches/matches/create-deployment
=== RUN   TestMatches/matches/deployment-matches-expected-fields
=== NAME  TestMatches/matches
    run.go:97: assertion failed: timeout exceeded (20s)
--- FAIL: TestMatches (20.16s)
    --- FAIL: TestMatches/matches (20.13s)
        --- PASS: TestMatches/matches/create-deployment (0.01s)
        --- PASS: TestMatches/matches/deployment-matches-expected-fields (19.82s)
```

Note, the overall test scenario (matches.yaml) produces a FAIL (as it should), however the failure is from the timeout exceeded instead of the assertion failure that last occurred before the timeout fired. And, worse, the test *unit* (deployment-matches-expected-fields) returns PASS where it should return FAIL.
